### ISSUE TITLE
How to use this repo

### ISSUE THREAD

**Issue by umfundii** [iit-DLSLab/Quadruped-PyMPC#1]
Hey, 

This looks amazing, and I am hoping to use it in my project. Could you please provide instructions on how to use this repository? Additionally, would it be possible for you to provide the code you used to produce the experiment shown in the README? 

Also, there are a couple of minor issues: the README contains some typos (the 'mamba_environment.yml' is inside the simulation folder), and 't_render' needs to be installed.

Thanks.

**Comment by giulioturrisi** [comment]
Hello,

thanks for the tips. I added a section in the README to explain how the simulation can be run.
