### ISSUE TITLE
deal with rough terrain

### ISSUE THREAD

**Issue by zhxiaoyu218** [iit-DLSLab/Quadruped-PyMPC#14]
I interested in if this work could deal with rough terrain, e.g. wave or uneven

**Comment by giulioturrisi** [comment]
Yes it can. Just change the string here 
https://github.com/iit-DLSLab/Quadruped-PyMPC/blob/4d6437c67e66eecdb29bfac70732edeee412b363/quadruped_pympc/config.py#L198
to modify the terrain. For the stairs, the swing gain in the same config file maybe are too big, and should be reduced
