### ISSUE TITLE
Execution error of simulation.py

### ISSUE THREAD

**Issue by robokang** [iit-DLSLab/Quadruped-PyMPC#19]
Hello, when I installed Quadruped-PyMPC and tried to run the simulation.py file, I get the following error.

```
Traceback (most recent call last):
  File ".../simulation/simulation.py", line 23, in <module>
    from quadruped_pympc.quadruped_pympc_wrapper import QuadrupedPyMPC_Wrapper
  File ".../quadruped_pympc/quadruped_pympc_wrapper.py", line 2, in <module>
    from quadruped_pympc.interfaces.srbd_batched_controller_interface import SRBDBatchedControllerInterface
  File ".../quadruped_pympc/interfaces/srbd_batched_controller_interface.py", line 3, in <module>
    from quadruped_pympc.helpers.periodic_gait_generator import PeriodicGaitGenerator
  File ".../quadruped_pympc/helpers/periodic_gait_generator.py", line 6, in <module>
    class PeriodicGaitGenerator:
  File ".../quadruped_pympc/helpers/periodic_gait_generator.py", line 74, in PeriodicGaitGenerator
    def set_phase_signal(self, phase_signal: np.ndarray, init: np.ndarray | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

If there is any way to solve this problem, please let me know.

**Comment by robokang** [comment]
It seems to be a problem with the python version. I did a clean install from scratch and that fixed the problem for now, thank you.

**Comment by Danfoa** [comment]
To support older versions of python while using the new versions typing structure / nomenclature we can add this import line to each file 

```
from __future__ import annotations 
```

This ensures annotations, including the typing structure used in new python versions, such as the one generating this issue, can be safely used in older python versions.

We should do this to keep backward compatibility as it incurred in 0 error / cost
