### ISSUE TITLE
Load terrains programatically

### ISSUE THREAD

**Issue by Danfoa** [iit-DLSLab/Quadruped-PyMPC#7]
Enable users to select different template terrains to load into the scene and define their own, terrain building function returning the XML body describing the ground/floor

**Comment by giulioturrisi** [comment]
ideally it would be nice to even give the possibility to randomize the terrain within a template

**Comment by giulioturrisi** [comment]
Added most of the feature in https://github.com/iit-DLSLab/gym-quadruped/pull/9. We can continue the discussion in the PR and here https://github.com/iit-DLSLab/gym-quadruped/issues/5
